name: Run Tests

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: ArtiomTr/jest-coverage-report-action@v2