name: 'coverage'
on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  coverage:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: ArtiomTr/jest-coverage-report-action@v2
          with:
            coverage-file: report.json
            base-coverage-file: report.json